### ISSUE TITLE
July edition "Tech on Campus" entry

### ISSUE THREAD

**Issue by twitu** [7vik/sokoban#1]
Would be great if you could,
1. Clean up the code a bit, reduce duplication, use better idioms
2. Add instructions on how to run the program in you README
3. Add some explanation of how the code works, maybe as a diagram or logical flow of how the game loop is working

**Comment by 7vik** [comment]
Sure, I'll get to this

**Comment by twitu** [comment]
You could also add a small gif of the game actually being played. Please close this issue when you feel it's resolved.

**Comment by twitu** [comment]
About point 2. please add instructions on how to install stack and how to run tests.

**Comment by 7vik** [comment]
I've added a GIF. I'm assuming Haskell is already installed so cabal stack should already be set up. I'll close this ig.
